name: Build and release gem

on:
  release:
    types: [published]

jobs:
  release:
    name: Release to gem hosts
    runs-on: ubuntu-latest
    steps:
      - name: Setup ruby
        uses: actions/setup-ruby@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem install git-lite-version-bump
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
      - name: Publish to GitHub
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: mitre
